language: python
python:
  - "3.5"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - sed -i '/ ssl_certificate: !secret ssl_cert/d' ./configuration.yaml
  - sed -i '/ ssl_key: !secret ssl_key' ./configuration.yaml



install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
